### ISSUE TITLE
冯诺依曼体系中cup类和memory类应该是平级关系

### ISSUE THREAD

**Issue by huawei00399896** [qiniu/arch#1]
最近在看您的架构课

1、定义cpu类时，我看类中包含了memory的引用（组成关系），个人觉得cpu和memory应该是平级关系，应该由上层一个更高级的类来包含cpu和memory，而不应该直接在cpu类中包含memory吧。
2、而且NewCPU的时候，memroy也作为参数传入了，搞得好像内存是初始化cpu必填的参数，个人觉得不应该，它们两者之间仅仅是连接关系。

**Comment by t4Wang** [comment]
我觉得你理解错了，这个不是外部内存，cpu是自带内存的，而且是必须有的。架构课你应该也看了，它的架构就是指令，存储加输入输出。像32位cpu不就带32bit的内存吗

**Comment by t4Wang** [comment]
> 最近在看您的架构课
> 
> 1、定义cpu类时，我看类中包含了memory的引用（组成关系），个人觉得cpu和memory应该是平级关系，应该由上层一个更高级的类来包含cpu和memory，而不应该直接在cpu类中包含memory吧。
> 2、而且NewCPU的时候，memroy也作为参数传入了，搞得好像内存是初始化cpu必填的参数，个人觉得不应该，它们两者之间仅仅是连接关系。

我觉得你理解错了，这个不是外部内存，cpu是自带内存的，而且是必须有的。架构课你应该也看了，它的架构就是指令，存储加输入输出。像32位cpu不就带32bit的内存吗

**Comment by huawei00399896** [comment]
感谢，理解了

**Comment by xushiwei** [comment]
如果CPU初始化不知道内存，它启动以后怎么读取指令呢？所以Memory参数是必须的。

**Comment by huawei00399896** [comment]
> 如果CPU初始化不知道内存，它启动以后怎么读取指令呢？所以Memory参数是必须的。

我对计算机组成原理知识还是有点欠缺，需要提高
